backend/adrenalina/config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  resources :eventos
  resources :localidads
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

backend/adrenalina/app/models/evento.rb
class Evento < ApplicationRecord
  belongs_to :localidad
end

backend/adrenalina/app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
    
    if params[:fecha].present?
      @eventos = @eventos.where("fecha = ?", "#{params[:fecha]}")
    end
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:titulo, :descripcion, :fecha, :hora, :lugar, :imagen, :localidad_id)
    end
end

backend/adrenalina/app/helpers/eventos_helper.rb
module EventosHelper
end

backend/adrenalina/app/views/eventos/_form.html.erb
<%= form_with(model: evento, local: true) do |form| %>
  <% if evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% evento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha %>
  </div>

  <div class="field">
    <%= form.label :hora %>
    <%= form.time_select :hora %>
  </div>

  <div class="field">
    <%= form.label :lugar %>
    <%= form.text_field :lugar %>
  </div>

  <div class="field">
    <%= form.label :imagen %>
    <%= form.text_field :imagen %>
  </div>

  <div class="field">
    <%= form.label :localidad_id %>
    <%= form.text_field :localidad_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/adrenalina/app/views/eventos/edit.html.erb
<h1>Editing Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

backend/adrenalina/app/views/eventos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Eventos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descripcion</th>
      <th>Fecha</th>
      <th>Hora</th>
      <th>Lugar</th>
      <th>Imagen</th>
      <th>Localidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= evento.titulo %></td>
        <td><%= evento.descripcion %></td>
        <td><%= evento.fecha %></td>
        <td><%= evento.hora %></td>
        <td><%= evento.lugar %></td>
        <td><%= evento.imagen %></td>
        <td><%= evento.localidad %></td>
        <td><%= link_to 'Show', evento %></td>
        <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
        <td><%= link_to 'Destroy', evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evento', new_evento_path %>

backend/adrenalina/app/views/eventos/new.html.erb
<h1>New Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Back', eventos_path %>

backend/adrenalina/app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @evento.titulo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @evento.descripcion %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @evento.fecha %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @evento.hora %>
</p>

<p>
  <strong>Lugar:</strong>
  <%= @evento.lugar %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= @evento.imagen %>
</p>

<p>
  <strong>Localidad:</strong>
  <%= @evento.localidad %>
</p>

<%= link_to 'Edit', edit_evento_path(@evento) %> |
<%= link_to 'Back', eventos_path %>