backend/adrenalina/config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  resources :eventos
  resources :localidads
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

backend/adrenalina/app/models/localidad.rb
class Localidad < ApplicationRecord
    has_many :usuarios
end

backend/adrenalina/app/controllers/localidads_controller.rb
class LocalidadsController < ApplicationController
  before_action :set_localidad, only: [:show, :edit, :update, :destroy]

  # GET /localidads
  # GET /localidads.json
  def index
    @localidads = Localidad.all
  end

  # GET /localidads/1
  # GET /localidads/1.json
  def show
  end

  # GET /localidads/new
  def new
    @localidad = Localidad.new
  end

  # GET /localidads/1/edit
  def edit
  end

  # POST /localidads
  # POST /localidads.json
  def create
    @localidad = Localidad.new(localidad_params)

    respond_to do |format|
      if @localidad.save
        format.html { redirect_to @localidad, notice: 'Localidad was successfully created.' }
        format.json { render :show, status: :created, location: @localidad }
      else
        format.html { render :new }
        format.json { render json: @localidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /localidads/1
  # PATCH/PUT /localidads/1.json
  def update
    respond_to do |format|
      if @localidad.update(localidad_params)
        format.html { redirect_to @localidad, notice: 'Localidad was successfully updated.' }
        format.json { render :show, status: :ok, location: @localidad }
      else
        format.html { render :edit }
        format.json { render json: @localidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localidads/1
  # DELETE /localidads/1.json
  def destroy
    @localidad.destroy
    respond_to do |format|
      format.html { redirect_to localidads_url, notice: 'Localidad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_localidad
      @localidad = Localidad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def localidad_params
      params.require(:localidad).permit(:nombre)
    end
end

backend/adrenalina/app/helpers/localidads_helper.rb
module LocalidadsHelper
end

backend/adrenalina/app/views/localidads/_form.html.erb
<%= form_with(model: localidad, local: true) do |form| %>
  <% if localidad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(localidad.errors.count, "error") %> prohibited this localidad from being saved:</h2>

      <ul>
      <% localidad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/adrenalina/app/views/localidads/edit.html.erb
<h1>Editing Localidad</h1>

<%= render 'form', localidad: @localidad %>

<%= link_to 'Show', @localidad %> |
<%= link_to 'Back', localidads_path %>

backend/adrenalina/app/views/localidads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Localidads</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @localidads.each do |localidad| %>
      <tr>
        <td><%= localidad.nombre %></td>
        <td><%= link_to 'Show', localidad %></td>
        <td><%= link_to 'Edit', edit_localidad_path(localidad) %></td>
        <td><%= link_to 'Destroy', localidad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Localidad', new_localidad_path %>

backend/adrenalina/app/views/localidads/new.html.erb
<h1>New Localidad</h1>

<%= render 'form', localidad: @localidad %>

<%= link_to 'Back', localidads_path %>

backend/adrenalina/app/views/localidads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @localidad.nombre %>
</p>

<%= link_to 'Edit', edit_localidad_path(@localidad) %> |
<%= link_to 'Back', localidads_path %>